### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by shaikhriyaz** [victorfern91/base64#1]
just cloned repository. Installed dependency and run the test but unfortunately, tests failed.

**Comment by victorfern91** [comment]
can you send me your test report? thanks

**Comment by victorfern91** [comment]
Probably is a problem with your environment. I created a new branch from master and the tests have passed successfully. You can see build report in [travis](https://travis-ci.org/victorfern91/base64/builds/202932864)

**Comment by shaikhriyaz** [comment]
Sorry for a Late reply. The problem was with my environment. Solved it. Thank you
